/*     
 *    
 *  Author     : Dev Dipak Patel & Vamsi Krishna Satyanarayana Vasa
 *  Version    : DEVSJAVA 2.7 
 *  Date       : 11-16-2023
 */
package Component.BasicProcessor;

import java.awt.*;

import GenCol.*;


import model.modeling.*;
import model.simulation.*;

import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;
import view.simView.*;



public class Skateboard_coupled extends ViewableDigraph{


public Skateboard_coupled(){
    super("gpt");

    ViewableAtomic g = new SkateboardGenerator("generator",10);
    ViewableAtomic s = new Skateboard("skateboard",5);
    ViewableAtomic t = new SkateboardTransducer("transducer",370);

     add(g);
     add(s);
     add(t);

//    addInport("in");
    addInport("start");
    addInport("stop");
    addOutport("ActualSpeed");
    addOutport("DesiredSpeed");
    addOutport("Avgtime");

    addTestInput("start", new entity(""));
    addTestInput("stop", new entity(""));

     addCoupling(this,"start",g,"start");
     addCoupling(this,"start",s,"start");
     addCoupling(this,"start",t,"start");
     
     addCoupling(this,"stop",g,"stop");
     addCoupling(this,"stop",s,"stop");
     addCoupling(this,"stop",t,"stop");
     
     addCoupling(g,"desired_speed_out",s,"in");
     addCoupling(g,"desired_speed_out",t,"desired_speed_in");

     addCoupling(s,"out",t,"actual_speed_in");

     addCoupling(t,"ActualSpeed",this,"ActualSpeed");
     addCoupling(t,"DesiredSpeed",this,"DesiredSpeed");
     addCoupling(t,"Avgtime",this,"Avgtime");

}
   
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 269);
        ((ViewableComponent)withName("transducer")).setPreferredLocation(new Point(63, 178));
        ((ViewableComponent)withName("skateboard")).setPreferredLocation(new Point(254, 47));
        ((ViewableComponent)withName("generator")).setPreferredLocation(new Point(50, 49));
    }
}
